# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [89]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

import math

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [90]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

In [91]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    'applicants_data.csv'
)

# Review the DataFrame
applicant_data_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [92]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [93]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN', 'NAME'])

# Review the DataFrame
applicant_data_df.head()

  APPLICATION_TYPE       AFFILIATION  ... ASK_AMT IS_SUCCESSFUL
0              T10       Independent  ...    5000             1
1               T3       Independent  ...  108590             1
2               T5  CompanySponsored  ...    5000             0
3               T3  CompanySponsored  ...    6692             1
4               T3       Independent  ...  142590             1

[5 rows x 10 columns]

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [94]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
display(categorical_variables)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [95]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [96]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [97]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

   APPLICATION_TYPE_T10  ...  SPECIAL_CONSIDERATIONS_Y
0                   1.0  ...                       0.0
1                   0.0  ...                       0.0
2                   0.0  ...                       0.0
3                   0.0  ...                       0.0
4                   0.0  ...                       0.0

[5 rows x 114 columns]

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [98]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df.drop(columns=categorical_variables)], axis=1)

# Review the Dataframe
encoded_df.head()

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  ASK_AMT  IS_SUCCESSFUL
0                   1.0                   0.0  ...     5000              1
1                   0.0                   0.0  ...   108590              1
2                   0.0                   0.0  ...     5000              0
3                   0.0                   0.0  ...     6692              1
4                   0.0                   0.0  ...   142590              1

[5 rows x 117 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [99]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
# YOUR CODE HERE
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [100]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
# YOUR CODE HERE
X[:5]

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  STATUS  ASK_AMT
0                   1.0                   0.0  ...       1     5000
1                   0.0                   0.0  ...       1   108590
2                   0.0                   0.0  ...       1     5000
3                   0.0                   0.0  ...       1     6692
4                   0.0                   0.0  ...       1   142590

[5 rows x 116 columns]

### Step 6: Split the features and target sets into training and testing datasets.

In [101]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [102]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [103]:
# Define the the number of inputs (features) to the model
number_input_features = X_train_scaled.shape[1]

# Review the number of features
number_input_features

116

In [104]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [105]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 50

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

50

In [106]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 25

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

25

In [107]:
# Create the Sequential model instance
nn = Sequential()

In [108]:
# Add the first hidden layer
nn.add(
    Dense(input_dim=number_input_features, units=hidden_nodes_layer1, activation="relu")
)

In [109]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [110]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [111]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_18 (Dense)             (None, 50)                5850
_________________________________________________________________
dense_19 (Dense)             (None, 25)                1275
_________________________________________________________________
dense_20 (Dense)             (None, 1)                 26
=================================================================
Total params: 7,151
Trainable params: 7,151
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [112]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [113]:
# Fit the model using 50 epochs and the training data
model_1 = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5790 - accuracy: 0.7187
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7301
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7310
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7310
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7330
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7341
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7340
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7345
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7360
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7345
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7350
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7363
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7356
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7365
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7352
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7374
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7372
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7373
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7373
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7369
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7373
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7386
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7383
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7379
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7378
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7385
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7381
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7397
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7391
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7379
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7389
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7395
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7394
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7397
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7394
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7396
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7397
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7388
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7387
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7406
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7407
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7398
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7409
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7396
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7404
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7401
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7400

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [114]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5567 - accuracy: 0.7298
Loss: 0.5566784739494324, Accuracy: 0.7297959327697754

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [130]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [117]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [118]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [119]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = math.floor((number_input_features + number_output_neurons_A1) / 2)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [120]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 = math.floor((hidden_nodes_layer1_A1 + number_output_neurons_A1) / 2)

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A1

29

In [121]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [122]:
# First hidden layer
nn_A1.add(
    Dense(input_dim=number_input_features, units=hidden_nodes_layer1_A1, activation="relu")
)

# Second hidden layer
nn_A1.add(
    Dense(units=hidden_nodes_layer2_A1, activation="relu")
)

# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="sigmoid"))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_21 (Dense)             (None, 58)                6786
_________________________________________________________________
dense_22 (Dense)             (None, 29)                1711
_________________________________________________________________
dense_23 (Dense)             (None, 1)                 30
=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [123]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [124]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5781 - accuracy: 0.7184
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7292
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7320
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7327
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7326
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7334
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7349
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7349
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7359
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7357
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7357
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7373
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7374
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7364
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7384
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7372
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7384
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7383
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7382
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7393
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7387
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7391
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7389
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7396
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7406
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7389
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7400
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7404
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7402
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7401
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7398
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7404
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7397
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7408
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7391
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7406
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7411
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7410
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7405
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7399
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7404
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7412

#### Alternative Model 2

In [142]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [143]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [144]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = math.floor((number_input_features + number_output_neurons_A2) / 2)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

58

In [145]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [146]:
# First hidden layer
nn_A2.add(
    Dense(input_dim=number_input_features, units=hidden_nodes_layer1_A2, activation="relu")
)

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_27 (Dense)             (None, 58)                6786
_________________________________________________________________
dense_28 (Dense)             (None, 1)                 59
=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [147]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [148]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5795 - accuracy: 0.7205
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7284
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7304
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7310
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7310
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7318
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7302
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7323
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7315
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7325
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7321
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7317
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7336
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7336
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7334
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7320
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7336
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7331
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7330
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7341
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7341
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7355
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7339
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7348
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7337
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7352
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7350
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7354
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7350
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7356
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7354
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7350
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7353
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7349
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7350
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7358
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7354
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7373
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7372
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7362
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7367
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7358
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7364
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7374
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7361
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7366
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7372
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7374
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7371

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [149]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5567 - accuracy: 0.7298
Loss: 0.5566784739494324, Accuracy: 0.7297959327697754

In [150]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5563 - accuracy: 0.7293
Loss: 0.5563185214996338, Accuracy: 0.7293294668197632

In [151]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5627 - accuracy: 0.7308
Loss: 0.5626900792121887, Accuracy: 0.7308454513549805

### Step 3: Save each of your alternative models as an HDF5 file.

In [152]:
# Set the file path for the first alternative model
file_path = "AlphabetSoup_A1.h5"

# Export your model to a HDF5 file
nn_A1.save_weights(file_path)

In [153]:
# Set the file path for the second alternative model
file_path = "AlphabetSoup_A2.h5"

# Export your model to a HDF5 file
nn_A2.save_weights(file_path)